[build]
  command = "npm run build"
  publish = "frontend"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# https://docs.netlify.com/build/configure-builds/file-based-configuration/#functions
[functions]
  included_files = ["src/**/*.ts"]
  node_bundler = "esbuild"